### ISSUE TITLE
why full date string?

### ISSUE THREAD

**Issue by evanwill** [uidaholib/spec-lumber#12]
@dcnb at some point you add full date string to the rake task to generate a post file, https://github.com/uidaholib/spec-lumber/commit/375454083875d0b2f96705d9e67e48509adc7d2b

I can't figure out why? 
Most posts don't have a full date string and just use yyyy-mm-dd. They don't really need one at all since it also gets pulled first from the required filename convention. front matter date basically overwrites the date, and that seems to work with either style date. I don't see any reason for the full date string, but it does make it annoying to work with the dates. Does it need to be in there?

**Comment by dcnb** [comment]
I think they were having trouble with making a post and then having them
not actually post because of time of day. I will have to look more closely
but I remember that being a problem. Something with the gmt time — it also
happened with future posts.
